### YamlMime:Yaml
# ms.openlocfilehash: 32819343100f4d8212e660497c1dd9a1e652711a
# ms.sourcegitcommit: 52128e1e0cb6e7de6806013aec318b8c01dd2376
# ms.translationtype: HT
# ms.contentlocale: ja-JP
# ms.lasthandoff: 02/14/2021
# ms.locfileid: "104284474"
parameters:
  buildConfiguration: Release
steps:
  - task: DotNetCoreCLI@2
    displayName: Build the project - ${{ parameters.buildConfiguration }}
    inputs:
      command: build
      arguments: --no-restore --configuration ${{ parameters.buildConfiguration }}
      projects: "**/*.csproj"
  - task: DotNetCoreCLI@2
    displayName: Publish the project - ${{ parameters.buildConfiguration }}
    inputs:
      command: publish
      projects: "**/*.csproj"
      publishWebProjects: false
      arguments: --no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}
      zipAfterPublish: true
